GET http://localhost:5000/posts

###

POST http://localhost:5000/createPost
Content-Type: application/json

{
    "title":"Taj Mahal"
}

###
DELETE  http://localhost:5000/60ef6a2c3d1cdcf7ac4fd101
Content-Type: application/json

{
    "id":"60ef6a2c3d1cdcf7ac4fd101"
}